use_frameworks!

platform :ios, '9.0'

target 'ModelPrivate_Example' do
  pod 'ModelPrivate', :path => '../'

  target 'ModelPrivate_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
